package com.techwith.ui.LocatorsPage;
import org.openqa.selenium.By;
import org.springframework.stereotype.Component;

@Component
public class Locators {
    public By email = By.xpath("//input[@id='textfield-login-username']");
    public By password = By.xpath("//input[@id='textfield-login-password']");
    public By SignInBtn = By.xpath("//button[@id='button-login']");
    public By Welcometolastbounce = By.xpath("//p[@class='login-subheader']");
    public By logo = By.xpath("//img[@class='login-lb-logo']");
    public By EmptyCredErrorMsg = By.xpath("//p[normalize-space()='Please input username and password']");
    public By PopUpBox = By.xpath("//p[text()='Incorrect username or password']");
    public By UsernamePasserrMes = By.xpath("//p[text()='Please input username and password']");

    public By InvaliCredErrorMsg = By.xpath("//p[normalize-space()='Incorrect username or password']");
    public By accounticonclick=By.xpath("//p[normalize-space()='Account']");
    public By Logout=By.xpath("//p[@id='p-navitem-account-logout']");
    public By VerifyBtn = By.xpath("(//p[normalize-space()='Verify'])[1]");
    public By VerifyNavigation = By.xpath("(//p[normalize-space()='Verify'])[1]");
    public By VerifySubmenu1 = By.xpath("(//p[normalize-space()='List Verify'])[1]");
    public By VerifySubmenu2  = By.xpath("(//p[normalize-space()='Single Verify'])[1]");
    public By NoOfDaysFilter=By.xpath("//div[@id='select-dashboard-single-filter-days']");

    public By SingleActivityDaysFilter1=By.xpath("//p[text()='7 Days']");
    public By SingleActivityDaysFilter2=By.xpath("//p[text()='15 Days']");
    public By SingleActivityDaysFilter3=By.xpath("//p[text()='30 Days']");
    public By DashboardPage = By.xpath("(//p[contains(text(),'Dashboard')])[1]");
    public By PhoneCheckNavigation = By.xpath("(//p[contains(text(),'Phone Check')])[1]");
    public By AccountBtn = By.xpath("(//p[normalize-space()='Account'])[1]");
    public By AccountNavigation = By.xpath("(//p[normalize-space()='Account'])[1]");
    public By LogoutSubmenu = By.xpath("(//p[contains(text(),'Logout')])[1]");
    public By SingalActivitydaysfilter15 = By.xpath("//div[text()='15 Days']");
    public By ListActivityChartResponceFilter=By.xpath("//div[@id='select-dashboard-list-filter-status']");
    public By AllResponseBtn=By.xpath("//p[text()='All']");
    public By ListActivityValid=By.xpath("(//span[text()='Valid'])[1]");
    public By ListActivityInvalid=By.xpath("(//span[text()='Invalid'])[1]");
    public By ListActivityRisky=By.xpath("(//span[text()='Risky'])[1]");
    public By ListActivityAcceptAll=By.xpath("(//span[text()='Accept All'])[1]");
    public By ListActivityUnknown=By.xpath("(//span[text()='Unknown'])[1]");
    public By DashboardLastBouncelogo=By.xpath("//div[@class='navbar-logo-container']");
    public By DashboardTopnavigationbar =By.xpath("//div[@class='navbar-container']");
    public By DashboardListActivityChart =By.xpath("//p[text()='List Activity']");
    public By DashboardSingleActivityChart=By.xpath("//div[@id='intro-dashboard-single-activity-chart']");
    public static By DashboardListHistoryTable=By.xpath("//div[@id='intro-list-verify-results-history-table']");
    public By DashboardSingleHistoryChart=By.xpath("//div[@id='intro-single-verify-results-history-table']");
    public By DashboardSupportsidepulloutwindow=By.xpath("//p[text()='Support']");
    public By DashboardFunctionalityfooter=By.xpath("//div[@class='footer-left']//p[text()='Functionality']");
    public By DashboardKnowledgefooter=By.xpath("(//div[@class='footer-left']//p[text()='Knowledge'])[1]");
    public By DashboardComplexVerificationSimplifiedfooter=By.xpath("(//div[@class='footer-middle'])");
    public By DashboardCopyrightinformation=By.xpath("(//div[@class='footer-bottom-middle'])[1]");
    public By DashboardDemandSciencelogo=By.xpath("//img[@id='img-footer-dsg']");
    public By DashboardPrivacyPolicylinks=By.xpath("//a[@href='https://demandscience.com/privacy-policy/']");
    public By DashboardTermsandConditionslink=By.xpath("//a[@href='https://demandscience.com/terms-of-use/']");
    public By DashboardSocialmedialinks=By.xpath("//a[@href='https://www.facebook.com/DemandScience/']");
    public By ResponseFilterButtonOnListActivityChart = By.xpath("(//div[@id='select-dashboard-list-filter-status'])[1]");
    public By clickOnTheNoOfDaysFilterOnListActivityChart = By.xpath("(//div[@id='select-dashboard-list-filter-days'])[1]");
    public By ListActivityResponseFilter1 = By.xpath("(//p[normalize-space()='Valid v Invalid'])[1]");
    public By ListActivityResponseFilter2 = By.xpath("(//p[contains(text(),'Valid')])[4]");
    public By ListActivityResponseFilter3 = By.xpath("(//p[contains(text(),'Invalid')])[5]");
    public By ListActivityResponseFilter4 = By.xpath("(//p[contains(text(),'Risky')])[2]");
    public By ListActivityResponseFilter5 = By.xpath("(//p[contains(text(),'Accept All')])[3]");
    public By ListActivityResponseFilter6 = By.xpath("(//p[contains(text(),'Unknown')])[2]");
    public By ListActivityResponseFilter7 = By.xpath("(//p[normalize-space()='All'])[1]");
    public By ListActivitydays15option = By.xpath("//div[@id='select-dashboard-list-filter-days']");
    public By ListHistoryTablefilename = By.xpath("(//p[@aria-label='LB-1141_10K_B.csv'][normalize-space()='LB-1141_10K_B.csv'])[1]");
    public By fileStatus = By.xpath("//td[@class='MuiTableCell-root MuiTableCell-body MuiTableCell-sizeMedium css-rvco39'][4]");
    public By ListHistoryTableFirstCsv = By.xpath("(//td[contains(@id,'tablecell-lv-ht-file-name')])[1]");
    public By supportpopup = By.xpath("//p[normalize-space()='Support']");
    public By ContactSupport = By.xpath("//p[normalize-space()='Contact Support']");
    public By facebookurl = By.xpath("//a[@href='https://www.facebook.com/DemandScience/']");
    public By twitterurl = By.xpath("//img[@id='img-footer-twitter-logo']");
    public By linkedinurl = By.xpath("//img[@id='img-footer-linkedin-logo']");
    public By termsandconditions = By.xpath("//a[normalize-space()='Terms & Conditions']");
    public By privacypolicy = By.xpath("//a[normalize-space()='Privacy Policy']");
    public By CCPA = By.xpath("//a[normalize-space()='CCPA']");
    public By complexverificationsimplifiedDSlink = By.xpath("//a[normalize-space()='DemandScience']");
    public By validemailsfooter = By.xpath("//div[contains(text(),'Valid Emails')]");
    public By riskyemailsfooter = By.xpath("//div[contains(text(),'Risky Emails')]");
    public By invalidemailsfooter = By.xpath("//div[contains(text(),'Invalid Emails')]");
    public By acceptallemailsfooter = By.xpath("//div[contains(text(),'Accept All Emails')]");
    public By unknownemailsfooter = By.xpath("//div[contains(text(),'Unknown Emails')]");
    public By dashboardfooterlink = By.xpath("//a[contains(text(),'Dashboard')]");
    public By listverifyfooterlink = By.xpath("//a[normalize-space()='List Verify']");
    public By singleverifyfooterlink = By.xpath("//a[normalize-space()='Single Verify']");
    public By singlehistoryhyperlink = By.xpath("//img[@id='img-dashboard-single-verify-link']");
    public By listverifyhyperlink = By.xpath("//img[@id='img-dashboard-list-verify-link']");
    public By listhistorpgnarrow = By.xpath("//td[@id='tablepagination-lv-ht-pagination']//button[@title='Go to next page']//*[name()='svg']");
    public By readystatustext = By.xpath("//p[text()='Ready']");
    public By preverifyResultdetails = By.xpath("//p[normalize-space()='Pre Verify Results']");
    public By batchfilename = By.xpath("//div[text()='LB-TestFileUpload.csv']");
    public By typosfound = By.xpath("//div[@id='listitemtext-lv-ht-verify-typos']");
    public By totalrecords = By.xpath("//div[@id='listitemtext-lv-ht-verify-records']");
    public By VerifyButton = By.xpath("//button[contains(@id,'button-lv-preclean-verify')]");
    public By FixTypo = By.xpath("//input[@id='switch-lv-upload']");
    public By Listverifysearch = By.xpath("//input[@id='input-base-search-lv-history']");
    public By singlehistorysearch = By.xpath("//input[@id='input-base-search-sv-history']");
    public By singlehistoryviewicon = By.xpath("//td[@class='MuiTableCell-root MuiTableCell-body MuiTableCell-sizeMedium css-zgfxhp']");
    public By singlehistorystatus = By.xpath("//p[normalize-space()='Status']");
    public By singlehistorymailserver = By.xpath("//p[normalize-space()='Mail Server']");
    public By singlehistoryattr = By.xpath("//p[normalize-space()='Attributes']");
    public By singlehistoremailtext = By.xpath("//p[@class='single-verification-results-email']");
    public By Uploadedtimestamp =By.xpath("(//span[contains(@class,'MuiTypography-root MuiTypography-bo')])[1]");
    public By Completedtimestamp =By.xpath("(//span[contains(@class,'MuiTypography-root MuiTypography-bo')])[2]");
    public By Totalnoofrecords =By.xpath("(//div[@id='listitemtext-lv-results-detail-totalRecords'])[1]");
    public By TotalnoofDuplicaterecords =By.xpath("(//div[@id='listitemtext-lv-results-detail-duplicates'])[1]");
    public By Responsesandtheirtotalpercentage =By.xpath("(//div[contains(@class,'MuiGrid-root MuiGrid-item MuiGrid-g')])[10]");
    public By percentagewhenhovered =By.xpath("(//div[contains(@id,'apexcharts')])[3]");
    public By complexverificationsimplifiedtext = By.xpath("//p[contains(text(),'LastBounce is the email intelligence platform by D')]");
    public By FileName = By.xpath("//span[@id='span-lv-ht-fileName']");
    public By Records = By.xpath("//span[@id='span-lv-ht-records']");
    public By Uploaded = By.xpath("//span[@id='span-lv-ht-uploaded']");
    public By Processed = By.xpath("//span[@id='span-lv-ht-processed']");
    public By Status = By.xpath("//span[@id='span-lv-ht-status']");
    public By Action = By.xpath("//th[@id='tablecell-lv-ht-action']");
    public By Delete = By.xpath("//th[@id='tablecell-lv-ht-delete']");
    public By View = By.xpath("//th[@id='tablecell-sv-history-table-accordion']");
    public By AllTab = By.xpath("//button[@id='tabs-lv-ht-all']");
    public By Completed = By.xpath("//button[@id='tabs-lv-ht-cleaned']");
    public By Verifying = By.xpath("//button[@id='tabs-lv-ht-verifying']");
    public By Readytoverify = By.xpath("//button[@id='tabs-lv-ht-ready']");
    public By Error = By.xpath("//button[@id='tabs-lv-ht-error']");
    public By Trash = By.xpath("//button[@id='tabs-lv-ht-trash']");
    public By configfileStatus = By.xpath("(//p[contains(@id,'tablecell-lv-ht-status-')])[2]");
    public By ResultHisConfigfile2 = By.xpath("(//td[contains(@id,'tablecell-lv-ht-file-name')])[2]");
    public By responseFilterOnSingleActivity = By.xpath("//div[@id='select-dashboard-single-filter-status']");
    public By SingleActivityValidNInvalid = By.xpath("(//p[normalize-space()='Valid v Invalid'])[1]");
    public By SingleActivityValid = By.xpath("(//p[@class='false'][normalize-space()='Valid'])[1]");
    public By SingleActivityInvalid = By.xpath("(//p[@class='false'][normalize-space()='Invalid'])[1]");
    public By SingleActivityRisky = By.xpath("(//p[@class='false'][normalize-space()='Risky'])[1]");
    public By SingleActivityAcceptAll = By.xpath("(//p[@class='false'][normalize-space()='Accept All'])[1]");
    public By SingleActivityUnknown = By.xpath("(//p[@class='false'][normalize-space()='Unknown'])[1]");
    public By SingleActivityAll = By.xpath("(//p[normalize-space()='All'])[1]");
    public By SingleActivityValidValidatn = By.xpath("//div[@id='line-chart-single']//div//span[contains(text(), 'Valid')]");
    public By SingleActivityInvalidValidatn = By.xpath("//div[@id='line-chart-single']//div//span[contains(text(), 'Invalid')]");
    public By SingleActivityRiskyValidatn = By.xpath("//div[@id='line-chart-single']//div//span[contains(text(), 'Risky')]");
    public By SingleActivityAcceptAllValidatn = By.xpath("//div[@id='line-chart-single']//div//span[contains(text(), 'Accept All')]");
    public By SingleActivityUnknownValidatn = By.xpath("//div[@id='line-chart-single']//div//span[contains(text(), 'Unknown')]");
    public By ListVerifypageHeading = By.xpath("//p[text()='List Verify']");
    public By ListVerifyFileUpload = By.xpath("//div[@id='lv-file-upload']");
    public By SingleVerifywindow = By.xpath("//p[text()='Single Verify']");
    public By ResultsHistorytable = By.xpath("//div[@id='intro-list-verify-results-history-table']");
    public By DragandDropYourCSVfilehereorclicktoupload = By.xpath("//p[text()='Drag & drop your CSV file here or click to upload']");
    public By Uploadicon = By.xpath("//img[contains(@src,'/static/media/upload-regular-grey')]");
    public By resultHistoryTableAllTab = By.xpath("//button[@id='tabs-lv-ht-all']");
    public By SingleVerifyText = By.xpath("(//p[normalize-space()='Single Verify'])[1]");
    public By EmailTextBox = By.xpath("(//div[@id='content-editable'])[1]");

}
